#!/usr/bin/env bash
# set -e
# set -u
# set -o pipefail

export CC=$(which hfuzz-clang)
export CXX=$(which hfuzz-clang++)
export AFL=$(which honggfuzz)

if [[ -z $1 ]];
then
    echo "Specify Example (single run)"
    exit -1
fi

if [[ -z $2 ]];
then
    echo "Specify Timeout (single run)"
    exit -1
fi

example=$1
timeout=$2

echo  ======== Compiling $example ========
echo "#define PHI 1 // generated by code2inv" > include/example_$example.h
./start.sh -b bin -o output -t tests -e example_$example

echo  ======== Executing $example ========
timeout $timeout ./fuzz.sh -b bin -o output -t tests -e example_$example

rm -rf *.fuzz *.TXT