#!/usr/bin/env bash

export CC=$(which hfuzz-clang)
export CXX=$(which hfuzz-clang++)
export AFL=$(which honggfuzz)

if [[ -z $1 ]];
then
    echo "Specify Timeout or example (single run)"
    exit -1
fi

for files in src/*.c;
do
    var=`echo $files | tr "/" "\n" | tr ".c" "\n" | grep ^[0-9]`
    if [[ -n $var ]];
    then
        example=$var
        timeout=$1
        
        echo "#define PHI 1 // generated by code2inv" > include/$example.h
        echo  ======== Compiling $example ========
        ./start.sh -b bin -o output -t tests -e $example
        
        echo  ======== Executing $example with timeout $1 ========
        timeout $timeout ./fuzz.sh -b bin -o output -t tests -e $example
    fi
done

rm -rf *.fuzz *.TXT