#define READ_FROM_FLAG 1 // generated by code2inv
#define PHI ( ( y >= 0 ) && ( a == ( y - b ) * x ) && ( x == r ) ) // generated by code2inv
long long int x = 0; // generated by code2inv
long long int y = 0; // generated by code2inv
long long int a = 0; // generated by code2inv
long long int b = 0; // generated by code2inv
long long int r = 2762893887441039360; // generated by code2inv
long long int shift = 93825153409712; // generated by code2inv
