#define READ_FROM_FLAG 1  // generated by code2inv
#define PHI \
    ((0 <= x) && (i <= n) && (y == fib(i - 1)) && (i == fib(i - 1)))  // generated by code2inv
long long int x = 0;                                                  // generated by code2inv
long long int y = 1;                                                  // generated by code2inv
long long int i = 0;                                                  // generated by code2inv
long long int n = 51;                                                 // generated by code2inv
