#define READ_FROM_FLAG 1 // generated by code2inv
#define PHI ( ( res == ( ( a + b + i ) ) ) && ( i <= n ) ) // generated by code2inv
long long int i = 1; // generated by code2inv
long long int n = 25700; // generated by code2inv
long long int a = 0; // generated by code2inv
long long int b = 0; // generated by code2inv
long long int res = 1; // generated by code2inv
