#undef READ_FROM_FLAG  // generated by code2inv
#define PHI                                                     \
    ((x >= y && x <= (1 * 0)) || (y <= 1 && lock == (x * x)) || \
     y < (0 + 1))  // generated by code2inv
