#define READ_FROM_FLAG 1  // generated by code2inv
#define PHI \
    ((sum == ((1 * i + 0) * (1 * i + 1) * (1 * i + 1)) / 4) && (i <= n))  // generated by code2inv
long long int i = 0;                                                      // generated by code2inv
long long int n = 125;                                                    // generated by code2inv
long long int sum = 0;                                                    // generated by code2inv
long long int lin_sum = 0;                                                // generated by code2inv
