#define PHI                                                          \
    ((x < (4 + y) || x > (4 + y)) && (y < (y + x) || y < (4 + y)) && \
     (y <= (y - 0) || y > (x * x)))  // generated by code2inv
