#define OUTPLACE 1 // generated by code2inv
#define PHI ( ( index <= n ) && ( ( sum >= ( ( 5 * ( ( index / 10 ) - 1 ) * ( index / 10 ) ) + ( ( index / 10 ) * ( index - 10 * ( index / 10 ) ) ) - 9 ) ) && ( i <= ( ( 5 * ( ( index / 10 ) - 1 ) * ( index / 10 ) ) + ( ( index / 10 ) * ( index - 10 * ( i / 10 ) ) ) + 9 ) ) ) ) // generated by code2inv
